name: "CodeQL Analysis"

on:
  workflow_call:
    inputs:
      DEFECTDOJO_PRODUCTID:
        required: true
        type: string
      DEFECTDOJO_PRODUCT_NAME:
        required: true
        type: string

jobs:
  codeql_analysis:
    name: Analyze Code with CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: "python"  # Ajusta según tu proyecto

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: codeql-results.sarif  # Guardar en el directorio raíz con este nombre

      - name: Upload CodeQL results as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: codeql-results.sarif

  codeql_create_engagement:
    name: Create engagement in DefectDojo - CodeQL
    needs: codeql_analysis
    runs-on: ubuntu-latest
    env:
      DEFECTDOJO_URL: "http://35.173.243.96:8080"
      DEFECTDOJO_TOKEN: "02dbd8bb2ab3071f94eacddd68d5d889b4edcda5"
      DEFECTDOJO_ENGAGEMENT_PERIOD: 28
      DEFECTDOJO_ENGAGEMENT_STATUS: "Not Started"
      DEFECTDOJO_ENGAGEMENT_BUILD_SERVER: null
      DEFECTDOJO_ENGAGEMENT_SOURCE_CODE_MANAGEMENT_SERVER: null
      DEFECTDOJO_ENGAGEMENT_ORCHESTRATION_ENGINE: null
      DEFECTDOJO_ENGAGEMENT_DEDUPLICATION_ON_ENGAGEMENT: false
      DEFECTDOJO_ENGAGEMENT_THREAT_MODEL: true
      DEFECTDOJO_ENGAGEMENT_API_TEST: true
      DEFECTDOJO_ENGAGEMENT_PEN_TEST: true
      DEFECTDOJO_ENGAGEMENT_CHECK_LIST: true
      DEFECTDOJO_PRODUCTID: ${{ inputs.DEFECTDOJO_PRODUCTID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq coreutils

      - name: Set engagement dates
        run: |
            echo "TODAY=$(date +%Y-%m-%d)" >> $GITHUB_ENV
            echo "ENDDAY=$(date -d '+28 days' +%Y-%m-%d)" >> $GITHUB_ENV


      - name: Create engagement in DefectDojo
        run: |
            curl --silent --show-error --location --request POST "${DEFECTDOJO_URL}/api/v2/engagements/" \
            --header "Authorization: Token ${DEFECTDOJO_TOKEN}" \
            --header "Content-Type: application/json" \
            --data '{
              "product": '${DEFECTDOJO_PRODUCTID}',
              "name": "CodeQL_#16698780642",
              "engagement_type": "CI/CD",
              "status": "In Progress",
              "target_start": "2025-08-02",
              "target_end": "2025-08-02"
            }' -o id.json
            
            # Extraer el ID y guardarlo en un archivo .env
            ENGAGEMENT_ID=$(jq -r '.id' id.json)
            echo "DEFECTDOJO_ENGAGEMENTID=${ENGAGEMENT_ID}" >> defectdojo1.env
            echo "DEFECTDOJO_ENGAGEMENTID=${ENGAGEMENT_ID}"

      - name: Upload defectdojo.env file
        uses: actions/upload-artifact@v4
        with:
          name: defectdojo1-env
          path: defectdojo1.env

  
  codeql_import_results:
    name: Publish CodeQL Scan in DefectDojo
    runs-on: ubuntu-latest
    needs: codeql_create_engagement
    env:
      DEFECTDOJO_URL: "http://35.173.243.96:8080"
      DEFECTDOJO_TOKEN: "02dbd8bb2ab3071f94eacddd68d5d889b4edcda5"
      DEFECTDOJO_SCAN_MINIMUM_SEVERITY: "Info"
      DEFECTDOJO_SCAN_ACTIVE: true
      DEFECTDOJO_SCAN_VERIFIED: false
      DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS: true
      DEFECTDOJO_SCAN_PUSH_TO_JIRA: false
      DEFECTDOJO_SCAN_ENVIRONMENT: "Default"
      DEFECTDOJO_SCAN_TEST_TYPE: "SARIF"
      DEFECTDOJO_PRODUCT_TYPE: "Github Actions"
      DEFECTDOJO_PRODUCT_NAME: ${{ inputs.DEFECTDOJO_PRODUCT_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download CodeQL results artifact
        uses: actions/download-artifact@v4
        with:
          name: codeql-results  # El nombre del artefacto que subiste

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Set scan date
        run: |
            echo "TODAY=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Upload CodeQL Scan to DefectDojo
        run: |
          curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
          -H "accept: application/json" \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
          -F "scan_date=${TODAY}" \
          -F "minimum_severity=${DEFECTDOJO_SCAN_MINIMUM_SEVERITY}" \
          -F "active=${DEFECTDOJO_SCAN_ACTIVE}" \
          -F "verified=${DEFECTDOJO_SCAN_VERIFIED}" \
          -F "scan_type=${DEFECTDOJO_SCAN_TEST_TYPE}" \
          -F "product_name=${DEFECTDOJO_PRODUCT_NAME}" \
          -F "file=@python.sarif;type=application/sarif+json" \
          -F "engagement_name=CodeQL_#${{ github.run_id }}" \
          -F "close_old_findings=${DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS}" \
          -F "push_to_jira=${DEFECTDOJO_SCAN_PUSH_TO_JIRA}"
